# Generated by Django 4.2.3 on 2023-07-18 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.TextField(verbose_name='Alamat')),
                ('status', models.IntegerField(choices=[(1, 'Aktif'), (0, 'Tidak Aktif')], default=0, verbose_name='Status')),
                ('telp', models.TextField(blank=True, null=True, verbose_name='Telp')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('update_dt', models.DateTimeField(blank=True, null=True, verbose_name='Update Date')),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data CIvil',
                'verbose_name_plural': 'Data Civil',
            },
        ),
    ]
