# Generated by Django 4.2.3 on 2023-07-21 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_datacivil_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namagroup', models.TextField(blank=True, null=True, verbose_name='Nama Group')),
            ],
            options={
                'verbose_name': 'Data Group',
                'verbose_name_plural': 'Data Group',
            },
        ),
        migrations.CreateModel(
            name='DataStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Data Status',
                'verbose_name_plural': 'Data Status',
            },
        ),
        migrations.AlterField(
            model_name='datacivil',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.datagroup'),
        ),
        migrations.AlterField(
            model_name='datacivil',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.datastatus'),
        ),
    ]
