# Generated by Django 4.2.3 on 2023-07-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_datagroup_datastatus_alter_datacivil_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagroup',
            name='intial',
            field=models.TextField(blank=True, null=True, verbose_name='Initial'),
        ),
    ]
