# Generated by Django 4.2.3 on 2023-07-21 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_datagroup_intial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datagroup',
            old_name='intial',
            new_name='initial',
        ),
    ]
